name: poppybossbattle
version: "${version}"
main: com.spectrasonic.poppybossbattle.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    poppybossbattle:
        aliases: [pobb]
        description: Comandos del plugin poppybossbattle
        permission: poppybossbattle.admin
    doey:
        permission: poppybossbattle.admin
    doeyboss:
        permission: poppybossbattle.admin
permissions:
    poppybossbattle.admin:
        default: op
    poppybossbattle.debug:
        description: Allows seeing debug messages
        default: op
